## Data Pipeline

### Sources

*The following citations represent the webpages or datasets from where the final dataset features were sourced.*

#### Endangered Languages Project (ELP/ELCAT)

Previous versions of this project utilized a CSV file from the Endangered Languages Project (ELP). Since then, ELP has shifted to hosting versions of their data on GitHub through the  ELCAT, a repository where they keep the dataset and each of its independent features as individual CSV files. This new data pipeline will dynamically pull the github repository to build a structured pandas dataframe, rather than working with the CSV from the earlier version of this project.

Catalogue of Endangered Languages. 2023. University of Hawaii at Manoa. http://www.endangeredlanguages.com

[ELCAT Github Link](https://github.com/cldf-datasets/elcat/tree/main)

#### Glottolog

Harald Hammarström, Robert Forkel, Martin Haspelmath, & Sebastian Bank. (2026). glottolog/glottolog: Glottolog database 5.3 (v5.3) [Data set]. Zenodo. https://doi.org/10.5281/zenodo.18840935

[Glottolog GitHub Link](https://github.com/glottolog/glottolog?tab=readme-ov-file)

#### Wikipedia

Wikipedia contributors. (2026, April 12). Languages used on the Internet. In Wikipedia, The Free Encyclopedia. Retrieved 18:29, April 28, 2026, from https://en.wikipedia.org/w/index.php?title=Languages_used_on_the_Internet&oldid=1348337473

Wikipedia contributors. (2026, April 24). List of languages by total number of speakers. In Wikipedia, The Free Encyclopedia. Retrieved 18:30, April 28, 2026, from https://en.wikipedia.org/w/index.php?title=List_of_languages_by_total_number_of_speakers&oldid=1350848572

Wikipedia contributors. (2026, April 14). List of official languages by country and territory. In Wikipedia, The Free Encyclopedia. Retrieved 18:22, April 28, 2026, from https://en.wikipedia.org/w/index.php?title=List_of_official_languages_by_country_and_territory&oldid=1348824802

#### World Bank

World Bank, World Development Indicators. (2024). GDP per capita (current US$) [Data file]. Retrieved from https://data.worldbank.org/indicator/NY.GDP.PCAP.CD

World Bank, World Development Indicators. (2024). Individuals using the internet (% of population) [Data file]. Retrieved from https://data.worldbank.org/indicator/IT.NET.USER.ZS

World Bank, World Development Indicators. (2024). Urban population (% of total population) [Data file]. Retrieved from https://data.worldbank.org/indicator/SP.URB.TOTL.IN.ZS

World Bank, World Development Indicators. (2024). Urban population growth (annual %) [Data file]. Retrieved from https://data.worldbank.org/indicator/SP.URB.GROW

## Features

|Target feature|Source|Notes|
|---|---|---|
|endangerment_level|Glottolog + ELCAT|Contains rankings of both endangered and non-endangered languages from multiple sources (including UNESCO and ethnologue). Use as the source of truth. Will need to be compared to ELCAT to reconcile discrepencies.|

|Feature Name|Source|Notes|
|---|---|---|
|language_name|Glottolog|Official name of the language. Will need to be compared across datasets to ensure consistency when joining.|
|iso_code|Glottolog|Currently labeled as "abbrv". Needs to be compared against glottolog iso codes when stacking the df. Wikipedia does not have iso codes, so will need to compare it against the name using regex standardization, possibly "other names" column from elp dataset. Use for stacking then drop before predictions.|
|speaker_number|ELCAT| Ordinal value, see https://github.com/cldf-datasets/elcat/blob/main/cldf/codes.csv for codes. This feature will be taken out to see if we can achieve high accuracy without it using the other features. This is beacuase number of speakers is a symptom, not a root cause.|
|speaker_number_trend|ELCAT|Ordinal value, see https://github.com/cldf-datasets/elcat/blob/main/cldf/codes.csv for codes.|
|transmission|ELCAT|Ordinal value, see https://github.com/cldf-datasets/elcat/blob/main/cldf/codes.csv for codes.|
domains_of_use|ELCAT|Ordinal value, see https://github.com/cldf-datasets/elcat/blob/main/cldf/codes.csv for codes.|
|lang_family|Glottolog|which language family a given language belongs to|
|lang_family_count|Glottolog (created)|count of other languages in the same family|
|country|Glottolog|list of countries where the language is spoken. Used for data cleaning and comparison, dropped before modeling|
|country_count|Glottolog (created)|number of countries where the language is spoken|
|macroarea|Glottolog|replaces continent since it is more indicative of the language than a continent is|
|official|Wikipedia|binary 1 if the language is recognized as an official language in any country|
|regional|Wikipedia| binary 1 if the language is recognized as a regional language in any country|
|national|Wikipedia|binary 1 if the language is recognized as a national language in any country|
|minority|Wikipedia|binary 1 if the language is recognized as a minority language in any country|
|widely_spoken|Wikipedia|binary 1 if the language is recognized as widely spoken in any country|
|internet_usage|Wikipedia|binary 1 if the language is used on the list of used on the internet (shows everything used above 0.1%)|
|max_gdp_percapita|World Bank| maximum gdp across the countries where the language is spoken|
|max_internet|World Bank|maximum internet usage across the countries where the language is spoken|
|max_urban|World Bank|maximum urban population % across the countries where the language is spoken|
|max_urban_growth|World Bank|maximum urban growth rate across countries where the language is spoken|
|avg_gdp_percapita|World Bank| average gdp per capita across the countries where the language is spoken|
|avg_urban|World Bank|average urban population % across the countries where the language is spoken|
|avg_internet|World Bank|average internet usage rate across the countries where the language is spoken|
|avg_urban_growth|World Bank|average urban growth rate across the countries where the language is spoken|

## Install Dependencies

In [ ]:
# Install packages if not already installed

#!pip install wbgapi
#!pip install pyglottolog
#!pip install wikipedia-api

In [1]:
# System
import os
import requests 

# Data Cleaning and Plotting
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import re
from rapidfuzz import process, fuzz
import pycountry

# Data APIs
import wikipediaapi as wiki
import wbgapi as wb
from pyglottolog import Glottolog

## Data Loading

*Dynamically pull data fom GitHub and API sources.*

### Endangered Languages Project (ELP/ELCAT)

*Note*: The updated GitHub repository for the Endangered Languages Catalogue has a slightly different format than the CSV that was previously used in this project. The new datasets include the following features:
- LEI (Language Endangerment Index): Represents the estimated endangerment level for each language.
- Speaker number: Ordinal variable represented by an integer for the estimated number of speakers.
- Speaker number trends: Ordinal variable represented by an integer for the estimated trends among communities (all members speak it, some members, etc.)
- Transmission: Ordinal variable represented by an integer for the estimated transmission from adults to children.
- Domains of use: Ordinal variable represented by an integer for which types of domains the language is used in (Government, Education, etc.)

In [2]:
# Pin latest commit

ELCAT_COMMIT = "main"

ELCAT_BASE_URL = f"https://raw.githubusercontent.com/cldf-datasets/elcat/{ELCAT_COMMIT}/cldf"

In [3]:
# Pull values.csv from ELCAT
PARAMS_TO_KEEP = ['speaker_number', 'transmission', 'speaker_number_trends', 'LEI', 'domains_of_use']

values = pd.read_csv(f"{ELCAT_BASE_URL}/values.csv")

# Filter to preferred values
preferred = values[(values['preferred'] == 'yes') & values['Parameter_ID'].isin(PARAMS_TO_KEEP)].copy()

print(preferred.groupby('Parameter_ID').size())

print('-'*50)

# Check for multiple preferred values per language
dupes = preferred.groupby(['Language_ID', 'Parameter_ID']).size()
print(f" Duplicate values found: {dupes[dupes > 1]}")

Parameter_ID
LEI                      3402
domains_of_use            584
speaker_number           3076
speaker_number_trends     778
transmission              942
dtype: int64
--------------------------------------------------
 Duplicate values found: Series([], dtype: int64)

In [4]:
# Create values dataframe
values_wide = preferred.pivot(index= 'Language_ID', columns= 'Parameter_ID', values= 'Value').reset_index()
values_wide.head()

Parameter_ID,Language_ID,LEI,domains_of_use,speaker_number,speaker_number_trends,transmission
0,21,"Endangered (100 percent certain, based on the ...",3,2,3,2
1,61,"Vulnerable (60 percent certain, based on the e...",NaN,1,NaN,0
2,101,"Endangered (100 percent certain, based on the ...",4,2,2,3
3,121,"Critically Endangered (60 percent certain, bas...",NaN,5,NaN,5
4,125,"Severely Endangered (100 percent certain, base...",4,3,5,4

In [5]:
# Load languages data
languages = pd.read_csv(f"{ELCAT_BASE_URL}/languages.csv")
languages.head()

,ID,Name,Macroarea,Latitude,Longitude,Glottocode,ISO639P3code,Comment,Countries,ELCatMacroareas,classification,endangerment,code_authorities,codes,alt_names
0,10009,Wampanoag,NaN,41.702591,-73.319119,wamp1249,wam,Massachusett-Narragansett was a complex of Sou...,US,North America,Algic,awakening,ISO 639-3,wam,Wôpanâak; Massachusett-Narragansett; Massach...
1,1001,Xipaya,NaN,-4.390200,-53.964800,xipa1240,xiy,NaN,BR,South America,Tupian,dormant,ISO 639-3,xiy,Shipaja; Xipaia; Shipaya; Chipaia; Xipáya; Šip...
2,1002,Yuchi,NaN,36.000900,-96.098800,yuch1247,yuc,NaN,US,North America,Isolate,critically endangered,ISO 639-3,yuc,Euchee
3,10029,Suabo,NaN,-2.100000,132.197000,suab1238,szp,NaN,ID,Southeast Asia,Trans-New Guinea,critically endangered,ISO 639-3,szp,Suabau; Inanwatan; Mirabo; Iagu; Solowat; Itig...
4,1003,Wichita,NaN,35.064700,-98.278800,wich1260,wic,NaN,US,North America,Caddoan,dormant,ISO 639-3,wic,Witchita

In [6]:
# Merge values and languages
elcat_df = pd.merge(values_wide, languages, 
                    left_on='Language_ID', 
                    right_on='ID', 
                    how='left').drop(columns= 'Language_ID')

elcat_df.head()

,LEI,domains_of_use,speaker_number,speaker_number_trends,transmission,ID,Name,Macroarea,Latitude,Longitude,Glottocode,ISO639P3code,Comment,Countries,ELCatMacroareas,classification,endangerment,code_authorities,codes,alt_names
0,"Endangered (100 percent certain, based on the ...",3,2,3,2,21,Namuyi,NaN,28.072700,101.956500,namu1246,nmy,NaN,CN,East Asia,Sino-Tibetan,endangered,ISO 639-3,nmy,Namuzi; 納木依; 納木義; 納木茲
1,"Vulnerable (60 percent certain, based on the e...",NaN,1,NaN,0,61,Himba,NaN,-18.056570,13.840657,zemb1238,dhm,NaN,NA AO,Africa,Niger-Congo,vulnerable,ISO 639-3,dhm,Dhimba; Dimba; Otjidhimba; Zemba; Tjimba; Simb...
2,"Endangered (100 percent certain, based on the ...",4,2,2,3,101,Kulaale,NaN,10.176552,18.566710,fani1244,fni,NaN,TD,Africa,Niger-Congo,endangered,ISO 639-3; Glottolog,fni; fani1244,Fagnia; Fanya; Fanyan; Fana; Fania; Fanian; Ma...
3,"Critically Endangered (60 percent certain, bas...",NaN,5,NaN,5,121,Potawatomi,NaN,39.325100,-95.849500,pota1247,pot,NaN,US CA,North America,Algic,critically endangered,ISO 639-3,pot,Pottawotomi; Bodéwadmi; Bodewadmi
4,"Severely Endangered (100 percent certain, base...",4,3,5,4,125,Hawaiian,NaN,21.894103,-160.161856,hawa1245,haw,NaN,US,North America,Austronesian,severely endangered,ISO 639-3,haw,'Ōlelo Hawai'i; 'Ōlelo Hawai'i Makuahine

### Glottolog Data

In [7]:
# Load data from github repository
GLOTTOLOG_PATH = "../Data/glottolog-5.3"

if not os.path.exists(GLOTTOLOG_PATH):
    !git clone --depth 1 --branch v5.3 https://github.com/glottolog/glottolog.git {GLOTTOLOG_PATH}

glottolog = Glottolog(GLOTTOLOG_PATH)

In [9]:
# Check data loaded correctly 
print(glottolog)

langs = list(glottolog.languoids())
print(f"Number of langoids loaded: {len(langs)}")

for lang in langs[:5]:
    print(f"ID: {lang.id}, Name: {lang.name}, Level: {lang.level}, Countries: {lang.countries}, Endangerment: {lang.endangerment.status.name if lang.endangerment else 'N/A'}")

<Glottolog repos v5.3 at /Users/jordan/github/Machine-Learning-Endangered-Languages/Data-Cleaning/../Data/glottolog-5.3>
Number of langoids loaded: 27177
ID: musk1252, Name: Muskogean, Level: LanguoidLevel(ordinal=1, id='family', description='sub-grouping of languoids above the language level'), Countries: [], Endangerment: N/A
ID: maba1274, Name: Maban, Level: LanguoidLevel(ordinal=1, id='family', description='sub-grouping of languoids above the language level'), Countries: [], Endangerment: N/A
ID: guri1248, Name: Muno, Level: LanguoidLevel(ordinal=2, id='language', description='defined by mutual non-intellegibility'), Countries: [Country(id='PG', name='Papua New Guinea')], Endangerment: shifting
ID: pawa1255, Name: Pawaia, Level: LanguoidLevel(ordinal=2, id='language', description='defined by mutual non-intellegibility'), Countries: [Country(id='PG', name='Papua New Guinea')], Endangerment: shifting
ID: bora1262, Name: Boran, Level: LanguoidLevel(ordinal=1, id='family', description='sub-grouping of languoids above the language level'), Countries: [], Endangerment: N/A

In [55]:
# Filter to language level
langauge_rows = []

for lang in langs:
    if lang.level.id == 'language':
        langauge_rows.append({
            'glottocode': lang.id,
            'name': lang.name,
            'level': lang.level.id,
            'iso_code': lang.iso,
            'macroarea': lang.macroareas[0].name if lang.macroareas else None,
            'countries': [c.id for c in lang.countries],
            'family_id': str(lang.lineage[0][1]) if lang.lineage else None,
            'family_name': str(lang.lineage[0][0]) if lang.lineage else None,
            'endangerment': lang.endangerment.status.name if lang.endangerment else None,
            'latitude': lang.latitude,
            'longitude': lang.longitude,
        })

glottolog_df = pd.DataFrame(langauge_rows)
print(glottolog_df.head())

  glottocode     name     level iso_code      macroarea countries family_id  \
0   guri1248     Muno  language      grx      Papunesia      [PG]      None
1   pawa1255   Pawaia  language      pwa      Papunesia      [PG]      None
2   guam1236    Guamo  language     None  South America      [VE]      None
3   dama1272    Damal  language      uhn      Papunesia      [ID]      None
4   puqu1242  Puquina  language      puq  South America      [BO]      None

  family_name endangerment   latitude   longitude
0        None     shifting  -3.571800  141.597000
1        None     shifting  -6.880210  145.081000
2        None      extinct   8.235103  -67.401875
3        None     shifting  -4.173450  137.496000
4        None      extinct -15.899200  -69.961100

In [11]:
# Make sure not all families are None
print(glottolog_df['family_name'].isna().value_counts())

False    8435
True      183
Name: family_name, dtype: int64

In [12]:
# Check coverage for endangerment column
glottolog_df['endangerment'].isna().value_counts()

False    8242
True      376
Name: endangerment, dtype: int64

In [13]:
# Check endangerment coverage by category
glottolog_df['endangerment'].value_counts()

not endangered    2831
shifting          1828
threatened        1599
extinct           1239
moribund           433
nearly extinct     312
Name: endangerment, dtype: int64

### Wikipedia Data

*Note*: for these pages, we know that the first table is the one relevant to this project, but make sure to check the actual url if an error occurs or if the table does not look right.

In [14]:
# Initialize Wikipedia API session
session = requests.Session()
session.headers.update({
    "User-Agent": "Predicting Endangered Languages (jordanandersen@berkeley.edu)"
})

wiki_wiki = wiki.Wikipedia(user_agent='MyProjectName (merlin@example.com)', language='en')

In [15]:
# Check that required pages exist
official_languages = wiki_wiki.page('List of official languages by country and territory')
print(f"Official languages page exists: {official_languages.exists()}")

top_20_languages = wiki_wiki.page('List of languages by number of native speakers')
print(f"Top 20 languages page exists: {top_20_languages.exists()}")

internet_languages = wiki_wiki.page('List of languages used on the Internet')
print(f"Internet languages page exists: {internet_languages.exists()}")

Official languages page exists: True
Top 20 languages page exists: True
Internet languages page exists: True

In [16]:
def extract_language_data(page):
    """
    Extracts data tables from a Wikipedia page and returns a DataFrame.
    """
    url = page.fullurl
    print(f"Extracting data from page: {page.title}: {page.fullurl}")

    response = session.get(url)
    response.raise_for_status()

    # Identify all tables on page
    tables = pd.read_html(response.text)
    print(f"Number of tables found: {len(tables)}")

    # Extract first table (may need to adjust if page structure changes)
    if tables:
        return tables[0]
    else:
        print(f"No tables found on page {page.title}")
        return None

In [17]:
official_languages = extract_language_data(official_languages)
official_languages.head()

Extracting data from page: List of official languages by country and territory: https://en.wikipedia.org/wiki/List_of_official_languages_by_country_and_territory
Number of tables found: 9

,Country/Region,Number of official (including de facto),Official language(s),Regional language(s),Minority language(s),National language(s),Widely spoken
0,Abkhazia[a],2,Abkhaz Russian,NaN,Georgian,Abkhaz,NaN
1,Afghanistan[1][2][3],2,Persian (Dari) Pashto,Uzbek[b] Turkmen[b] Pashayi[b] Nuristani[b] Ba...,NaN,Persian (Dari) Pashto,Persian (Dari)
2,Albania[4],1,Albanian,NaN,Greek Macedonian Aromanian,NaN,Italian
3,Algeria[5],2,Arabic Berber,NaN,NaN,Arabic Berber,French
4,Andorra,1,Catalan[6],NaN,Spanish French Portuguese,NaN,NaN

In [18]:
top_20_languages = extract_language_data(top_20_languages)
top_20_languages.head()

Extracting data from page: List of languages by number of native speakers: https://en.wikipedia.org/wiki/List_of_languages_by_number_of_native_speakers
Number of tables found: 8

           Language  Native speakers (millions) Language family      Branch
0  Mandarin Chinese                         988    Sino-Tibetan     Sinitic
1           Spanish                         487   Indo-European     Romance
2           English                         372   Indo-European    Germanic
3             Hindi                         347   Indo-European  Indo-Aryan
4        Portuguese                         252   Indo-European     Romance

In [19]:
internet_languages = extract_language_data(internet_languages)
internet_languages.head()

Extracting data from page: Languages used on the Internet: https://en.wikipedia.org/wiki/Languages_used_on_the_Internet
Number of tables found: 9

   Rank  Language 15 May 2023 3 December 2025
0     1   English       55.5%           49.3%
1     2   Spanish        5.0%            6.0%
2     3    German        4.3%            5.9%
3     4  Japanese        3.7%            5.1%
4     5    French        4.4%            4.5%

### World Bank Data

In [20]:
# Search for relevant indicators
wb.series.info(id=["SP.URB.GROW","SP.URB.TOTL.IN.ZS","IT.NET.USER.ZS","NY.GDP.PCAP.CD"])

id                 value
-----------------  ------------------------------------------------
NY.GDP.PCAP.CD     GDP per capita (current US$)
IT.NET.USER.ZS     Individuals using the Internet (% of population)
SP.URB.TOTL.IN.ZS  Urban population (% of total population)
SP.URB.GROW        Urban population growth (annual %)
                   4 elements

In [21]:
# Load GDP per capita last 10 years (current US$)
gdp = wb.data.DataFrame("NY.GDP.PCAP.CD", time=range(2014, 2025), labels=True).reset_index()
gdp.head()

,economy,Country,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020,YR2021,YR2022,YR2023,YR2024
0,ZWE,Zimbabwe,1372.915262,1387.126326,1408.139453,3445.449410,2270.895319,2184.329239,2059.674454,2613.605421,2536.400502,2195.224921,2497.203322
1,ZMB,Zambia,1707.485731,1295.877887,1239.085279,1483.465773,1463.899979,1258.986198,951.644317,1127.160779,1447.123101,1330.727806,1187.109434
2,YEM,"Yemen, Rep.",1430.164210,1362.173812,975.359417,811.165970,633.887202,NaN,NaN,NaN,NaN,NaN,NaN
3,PSE,West Bank and Gaza,3352.112595,3272.154324,3527.613824,3620.360487,3562.330943,3656.858271,3233.568638,3678.635657,3799.955270,3455.028529,2592.305912
4,VIR,Virgin Islands (U.S.),33045.364380,34007.352941,35324.974887,35365.069304,36663.208755,38633.529892,39787.374165,42571.077737,44320.909186,NaN,NaN

In [22]:
# Load % using internet last 10 years
internet = wb.data.DataFrame("IT.NET.USER.ZS", time=range(2014, 2025), labels=True).reset_index()
internet.head()

,economy,Country,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020,YR2021,YR2022,YR2023,YR2024
0,ZWE,Zimbabwe,16.364740,22.742800,23.120001,24.400000,25.000000,26.588301,29.298565,32.5924,36.256500,38.674801,41.642799
1,ZMB,Zambia,6.500000,8.800000,10.300000,12.200000,14.299997,14.471900,14.645800,14.8219,15.000000,16.450701,17.101000
2,YEM,"Yemen, Rep.",22.549999,24.085400,24.579201,NaN,NaN,17.490999,NaN,NaN,NaN,NaN,NaN
3,PSE,West Bank and Gaza,53.665200,56.700001,59.900002,63.299999,64.399994,70.622584,76.181602,NaN,88.646906,86.637653,NaN
4,VIR,Virgin Islands (U.S.),50.070000,54.839137,59.608316,64.377494,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
# Load urban % population last 10 years
urban_pop = wb.data.DataFrame("SP.URB.TOTL.IN.ZS", time=range(2014, 2025), labels=True).reset_index()
urban_pop.head()

,economy,Country,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020,YR2021,YR2022,YR2023,YR2024
0,ZWE,Zimbabwe,33.162808,33.561264,34.079946,34.701495,35.408554,36.183764,37.009767,37.869206,38.705521,39.291937,39.893372
1,ZMB,Zambia,41.563474,41.955510,42.344248,42.729598,43.111474,43.489786,43.864449,44.235373,44.598851,45.028585,45.470384
2,YEM,"Yemen, Rep.",31.862616,32.388318,32.951201,33.558691,34.210605,34.906756,35.702560,36.070495,36.322631,36.570798,36.807752
3,PSE,West Bank and Gaza,85.043334,85.218217,85.337739,85.378226,85.535113,85.813617,86.074118,86.334956,86.596142,86.857687,87.119601
4,VIR,Virgin Islands (U.S.),94.879707,94.941332,94.994109,95.036679,95.067678,95.085748,95.097402,95.160431,95.217151,95.274079,95.331220

In [27]:
# Load urban growth last 10 years (annual %)
urban_growth = wb.data.DataFrame("SP.URB.GROW", time=range(2014, 2025), labels=True).reset_index()
urban_growth.head()

,economy,Country,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020,YR2021,YR2022,YR2023,YR2024
0,ZWE,Zimbabwe,2.161444,2.534322,2.921846,3.250231,3.504475,3.729247,3.916481,4.021655,3.890609,3.180794,3.299572
1,ZMB,Zambia,4.127701,4.058949,4.016361,3.973471,3.895745,3.835322,3.761976,3.657400,3.581982,3.753005,3.788191
2,YEM,"Yemen, Rep.",4.394924,4.676698,4.725123,4.839049,4.884359,4.980809,5.127399,3.769546,3.569918,3.690719,3.627941
3,PSE,West Bank and Gaza,2.609577,2.495896,2.386264,2.036110,2.716618,2.836860,2.789635,2.759625,2.727602,2.694855,2.661359
4,VIR,Virgin Islands (U.S.),-0.074222,-0.092855,-0.126225,-0.174433,-0.228791,-0.291410,-0.343694,-0.329989,-0.372918,-0.411322,-0.456226

## Data Cleaning & Feature Creation

### ELCAT Cleaning

- Cast ordinal columns as integers

In [39]:
# Change ordinal columns to integers
ordinal_cols = ["domains_of_use", "speaker_number", "speaker_number_trends", "transmission"]

for col in ordinal_cols:
    elcat_df[col] = pd.Categorical(
        elcat_df[col].astype('Int64'),
        ordered=True
    )

print(elcat_df.dtypes)

LEI                        object
domains_of_use           category
speaker_number           category
speaker_number_trends    category
transmission             category
ID                          int64
Name                       object
Macroarea                 float64
Latitude                  float64
Longitude                 float64
Glottocode                 object
ISO639P3code               object
Comment                    object
Countries                  object
ELCatMacroareas            object
classification             object
endangerment               object
code_authorities           object
codes                      object
alt_names                  object
dtype: object

In [41]:
elcat_df['endangerment'].isna().value_counts()

False    3401
True        2
Name: endangerment, dtype: int64

In [42]:
elcat_df['endangerment'].value_counts()

threatened               921
endangered               763
vulnerable               548
critically endangered    433
severely endangered      385
dormant                  193
at risk                   87
awakening                 71
Name: endangerment, dtype: int64

### Glottolog Cleaning

- Create column for lang_family_count

In [43]:
# Create column for language family count

family_counts = glottolog_df['family_name'].value_counts()

glottolog_df['lang_family_count'] = glottolog_df['family_name'].map(family_counts)
print(glottolog_df[['family_name', 'lang_family_count']].tail())

print("-"*50)
print(f"Check a specific language family count to ensure mapping is correct")
print(glottolog_df[glottolog_df['family_name'] == 'Nivkh'])

        family_name  lang_family_count
8613  Lengua-Mascoy                6.0
8614  Lengua-Mascoy                6.0
8615  Lengua-Mascoy                6.0
8616          Nivkh                2.0
8617          Nivkh                2.0
--------------------------------------------------
Check a specific language family count to ensure mapping is correct
     glottocode        name     level iso_code macroarea countries family_id  \
8616   gily1242  Amur Nivkh  language      niv   Eurasia      [RU]  nivk1234
8617   sakh1247     Nighvng  language     None   Eurasia      [RU]  nivk1234

     family_name endangerment  latitude  longitude  lang_family_count
8616       Nivkh     moribund   52.5900   140.6810                2.0
8617       Nivkh     moribund   51.7814   143.1628                2.0

### World Bank Cleaning

- Pull the latest value for each country. If no value is available, input NaN
- Collapse World Bank data into one dataframe

In [44]:
def select_wb_value(wb_df, val_col_name):
    """Identify the year columns in the World Bank DataFrames 
    and select the most recent non-null value for each country. """

    year_cols = [col for col in wb_df.columns if re.match(r'YR\d{4}', str(col))]

    # Forward fill values across years and select the most recent non-null value for each country
    wb_df['_latest'] = wb_df[year_cols].ffill(axis=1).iloc[:, -1]

    # Rename resulting columns
    result = wb_df[['economy', 'Country', '_latest']].copy()
    result = result.rename(columns= {'_latest': val_col_name})

    return result

In [45]:
# Apply to all World Bank DataFrames

gdp_clean = select_wb_value(gdp, 'gdp_per_capita')
internet_clean = select_wb_value(internet, 'internet_users_pct')
urban_pop_clean = select_wb_value(urban_pop, 'urban_population_pct')
urban_growth_clean = select_wb_value(urban_growth, 'urban_growth_pct')

In [46]:
# Merge World Bank DataFrames

wb_merged = (gdp_clean.merge(internet_clean, on=['economy', 'Country'], how= 'left')
                        .merge(urban_pop_clean, on=['economy', 'Country'], how= 'left')
                        .merge(urban_growth_clean, on=['economy', 'Country'], how= 'left'))

wb_merged.head()

,economy,Country,gdp_per_capita,internet_users_pct,urban_population_pct,urban_growth_pct
0,ZWE,Zimbabwe,2497.203322,41.642799,39.893372,3.299572
1,ZMB,Zambia,1187.109434,17.101000,45.470384,3.788191
2,YEM,"Yemen, Rep.",633.887202,17.490999,36.807752,3.627941
3,PSE,West Bank and Gaza,2592.305912,86.637653,87.119601,2.661359
4,VIR,Virgin Islands (U.S.),44320.909186,64.377494,95.331220,-0.456226

## Combine DataFrames

**Strategy:**

Glottolog will serve as the spine for the dataframe merges since it contains 8,000+ languages, both endangered and non-endangered. From there, we will merge the additional dataframes into the glottolog data and fill in the features from the table above language by language.

**Approach:**

- Stage 1
    - Merge ELCAT to Glottolog on glottocode. 
    - Compare ELCAT and Glottolog endangerment labels. Both will be kept for now because I want to be able to filter down to the ELCAT languages now that I have more features to do an apples-to-apples comparison with our old model, but I then want to move towards using the glottolog labels since there are way more languages to try and get a more accurate model. 
- Stage 2
    - Aggregate world bank data based on country codes
- Stage 3
    -

### Stage 1: ELCAT + Glottolog

In [56]:
# Merge ELCAT to Glottolog on glottocode
elcat_cols = ['Glottocode', 
                'domains_of_use',
                'speaker_number',
                'speaker_number_trends',
                'transmission',
                'alt_names']

elcat_for_merge = elcat_df[elcat_cols + ['endangerment']].rename(columns={'endangerment': 'elcat_endangerment'})

master_df = glottolog_df.rename(columns={'endangerment': 'glott_endangerment'}
                                ).merge(
                                        elcat_for_merge,
                                       left_on='glottocode',
                                       right_on='Glottocode',
                                       how='left').drop(columns= 'Glottocode')

print(master_df.head())
print(f"Master dataframe shape: {master_df.shape}")
print(f"Languages with Glottolog endangerment: {master_df['glott_endangerment'].notna().sum()}")
print(f"Languages with ELCAT endangerment: {master_df['elcat_endangerment'].notna().sum()}")
print(f"Languages with both: {master_df[['glott_endangerment', 'elcat_endangerment']].notna().all(axis=1).sum()}")
print(f"Languages with neither: {master_df[['glott_endangerment', 'elcat_endangerment']].isna().all(axis=1).sum()}")

  glottocode     name     level iso_code      macroarea countries family_id  \
0   guri1248     Muno  language      grx      Papunesia      [PG]      None
1   pawa1255   Pawaia  language      pwa      Papunesia      [PG]      None
2   guam1236    Guamo  language     None  South America      [VE]      None
3   dama1272    Damal  language      uhn      Papunesia      [ID]      None
4   puqu1242  Puquina  language      puq  South America      [BO]      None

  family_name glott_endangerment   latitude   longitude domains_of_use  \
0        None           shifting  -3.571800  141.597000            NaN
1        None           shifting  -6.880210  145.081000            NaN
2        None            extinct   8.235103  -67.401875            NaN
3        None           shifting  -4.173450  137.496000            NaN
4        None            extinct -15.899200  -69.961100            NaN

  speaker_number speaker_number_trends transmission  \
0              3                   NaN          NaN
1              2                   NaN          NaN
2            NaN                   NaN          NaN
3              2                     2            2
4            NaN                   NaN          NaN

                                           alt_names elcat_endangerment
0                                              Menóu         endangered
1       Aurama; Pavaia; Pawaian; Sira; Tudahwe; Yasa         threatened
2                                                NaN                NaN
3  Uhunduni; Amung; Amung Kal; Amungme; Amuy; Eng...         threatened
4                                                NaN                NaN
Master dataframe shape: (8635, 17)
Languages with Glottolog endangerment: 8259
Languages with ELCAT endangerment: 3090
Languages with both: 3090
Languages with neither: 376

In [57]:
# Compare how ELCAT and Glottolog endangerment labbels map to each other
crosstab = pd.crosstab(
    master_df['glott_endangerment'].fillna('missing'),
    master_df['elcat_endangerment'].fillna('missing'),
    margins=True
)
crosstab

elcat_endangerment,at risk,awakening,critically endangered,dormant,endangered,missing,severely endangered,threatened,vulnerable,All
glott_endangerment,,,,,,,,,,
extinct,0,53,133,160,3,872,17,3,1,1242
missing,0,0,0,0,0,376,0,0,0,376
moribund,0,0,0,0,2,109,322,0,0,433
nearly extinct,0,0,248,0,1,60,3,0,0,312
not endangered,80,0,2,1,3,2727,1,12,6,2832
shifting,0,0,4,0,690,316,4,822,2,1838
threatened,1,0,1,0,8,1085,5,13,489,1602
All,81,53,388,161,707,5545,352,850,498,8635

### Stage 2: Add World Bank Values

In [58]:
def alpha2_to_alpha3(code):
    """Convert alpha-2 country code to alpha-3 using pycountry."""
    try: 
        return pycountry.countries.get(alpha_2=code.strip()).alpha_3
    except:
        return None

In [59]:
# Explode country lists to one row per (language, country) pair
lang_country = master_df[['glottocode', 'countries']].explode('countries').copy()
lang_country['economy'] = lang_country['countries'].map(alpha2_to_alpha3)
lang_country.head()

  glottocode countries economy
0   guri1248        PG     PNG
1   pawa1255        PG     PNG
2   guam1236        VE     VEN
3   dama1272        ID     IDN
4   puqu1242        BO     BOL

In [60]:
# Join World Bank data
lang_wb = lang_country.merge(
    wb_merged,
    on= 'economy',
    how= 'left'
)
lang_wb.sample(5)

,glottocode,countries,economy,Country,gdp_per_capita,internet_users_pct,urban_population_pct,urban_growth_pct
9447,muya1243,CM,CMR,Cameroon,1830.008337,46.258801,55.403175,3.109351
1235,siku1242,ID,IDN,Indonesia,4925.430488,72.780755,58.750964,1.897196
492,lore1244,VU,VUT,Vanuatu,3410.770232,22.351400,22.286693,2.370065
5799,tote1238,NA,NAM,Namibia,4413.127522,64.874603,50.408803,3.142308
9866,geez1241,ET,ETH,Ethiopia,1133.882797,21.941299,23.622284,4.998470

In [61]:
# Aggregate per language
wb_agg = lang_wb.groupby('glottocode').agg(
    country_count = ('economy', 'nunique'),
    max_gdp_percapita=('gdp_per_capita', 'max'),
    avg_gdp_percapita=('gdp_per_capita', 'mean'),
    max_internet=('internet_users_pct', 'max'),
    avg_internet=('internet_users_pct', 'mean'),
    max_urban=('urban_population_pct', 'max'),
    avg_urban=('urban_population_pct', 'mean'),
    max_urban_growth=('urban_growth_pct', 'max'),
    avg_urban_growth=('urban_growth_pct', 'mean'),
)

In [62]:
wb_agg.sample(10)

,country_count,max_gdp_percapita,avg_gdp_percapita,max_internet,avg_internet,max_urban,avg_urban,max_urban_growth,avg_urban_growth
glottocode,,,,,,,,,
ikul1238,1,1084.160418,1084.160418,41.211399,41.211399,62.975568,62.975568,3.362883,3.362883
laek1243,1,3006.705645,3006.705645,18.811600,18.811600,15.406182,15.406182,4.067855,4.067855
temb1278,1,10310.548878,10310.548878,84.463472,84.463472,87.895855,87.895855,0.724402,0.724402
horo1247,1,961.559756,961.559756,12.626900,12.626900,26.931529,26.931529,7.205344,7.205344
west2441,1,64603.985631,64603.985631,96.131401,96.131401,87.602147,87.602147,2.125713,2.125713
yopn1238,1,3006.705645,3006.705645,18.811600,18.811600,15.406182,15.406182,4.067855,4.067855
hata1243,1,4925.430488,4925.430488,72.780755,72.780755,58.750964,58.750964,1.897196,1.897196
pari1256,1,1080.147186,1080.147186,6.671000,6.671000,21.376819,21.376819,5.355726,5.355726
yoga1237,1,3984.831539,3984.831539,67.263009,67.263009,55.452098,55.452098,1.418546,1.418546
piem1238,3,84534.040784,63174.455937,96.131401,93.348641,87.602147,79.110560,2.125713,1.070288

In [67]:
master_df = master_df.merge(
    wb_agg,
    on= 'glottocode',
    how= 'left'
)

### Stage 3:

In [ ]:
def build_name_lookup(elcat_df, name_col="Name", alias_col="other_names"):
    """
    Returns a dict: normalized_name -> glottocode
    Covers both the official name and any aliases in other_names.
    """

    lookup = {}

    for _, row in elcat_df.iterrows():
        gc = row['Glottocode']
        
        # Primary name
        primary = str(row[name_col]).lower().strip()
        
        # Add to lookup
        lookup[primary] = gc

        # Add aliases if available
        if alias_col in elcat_df.columns and pd.notna(row[alias_col]):
            for alias in re.split(r'[,;|]', str(row[alias_col])):
                alias_norm = alias.strip().lower()
                if alias_norm and alias_norm not in lookup:
                    lookup[alias_norm] = gc
    
    return lookup

In [ ]:
# Apply to elcat dataframe

name_to_glottocode = build_name_lookup(elcat_df)
elcat_name_list = list(name_to_glottocode.keys())

In [ ]:
def fuzzy_match_to_glottocode(wiki_name_normalized, name_lookup, candidates, threshold= 85):
    """Tries to match a normalized Wikipedia language name to a Glottocode.
    
    Strategy:
        1. Exact match
        2. RapidFuzz best match above threshold (catches spelling variants, word order swaps, etc.)
        3. Returns None if no match reaches the confidence threshold
    """

    # Try exact match first